### ISSUE TITLE
Why is it necessary to ensure signature verified with the recovered key?

### ISSUE THREAD

**Issue by adam254689** [RustCrypto/signatures#751]
https://github.com/RustCrypto/signatures/blob/8516671bb56abe998d3e88d941df7862b6d58985/ecdsa/src/recovery.rs#L313C9-L313C47

I'm not super familiar with the details of ECDSA, but for my workload this `verify_prehash` check doubles the runtime. Is there any situation where this check will actually fail?

**Comment by tarcieri** [comment]
Computing the recovered key involves solving a system of linear equations.

If the signature doesn’t verify, an attacker can trick you into recovering the wrong key.

**Comment by adam254689** [comment]
> Computing the recovered key involves solving a system of linear equations.
> 
> If the signature doesn’t verify, an attacker can trick you into recovering the wrong key.

Can you elaborate a bit more on this? Would the system of linear equations not constrain that the recovered key verifies? A concrete example where `vk.verify_prehash(prehash, signature)` returns an error would be super useful.

**Comment by tarcieri** [comment]
> Would the system of linear equations not constrain that the recovered key verifies

It does not. An attacker can easily solve for whatever key they want if there is no requirement that the signature verifies.

**Comment by adam254689** [comment]
> > Would the system of linear equations not constrain that the recovered key verifies
> 
> It does not. An attacker can easily solve for whatever key they want if there is no requirement that the signature verifies.

Are you saying that if an attacker has control over the input, then `recover_from_prehash` can produce whatever verifying key they want, but in that case, the verification would return an error? If so, could you provide an example?

**Comment by tarcieri** [comment]
I’m currently on vacation and don’t have time to put together a contrived example for you

**Comment by XuJiandong** [comment]
In Bitcoin's secp256k1 implementation, the recovery routine doesn't include verification of the recovered public key. You can see this in the [Bitcoin secp256k1 code](https://github.com/bitcoin-core/secp256k1/blob/0055b86780f2aa7272a1c307f6b9cd298584340f/src/modules/recovery/main_impl.h#L137-L158).

If the recovered public key isn't correct, an error occurs when comparing it to the correct public key or public key hash. Therefore, we can skip this expensive verification.

**Comment by tarcieri** [comment]
I think it would be okay to add a separate `*_noverify` method or something like that, however it’s a much safer default to verify and not output potentially incorrect public keys

**Comment by pmikolajczyk41** [comment]
Hi @tarcieri, following up on the comment where you wrote:
> _An attacker can easily solve for whatever key they want if there is no requirement that the signature verifies._

I'm trying to understand the concrete attack. Walking through the math, the recovery formula is `pk = r⁻¹(sR − zG)`, where `R` is the curve point with x-coordinate `r` (up to taking mod) and `y`-parity selected by `recovery_id`. So an attacker who wants the recovery to yield a chosen target key `T` must satisfy: `r·T + z·G = s·R`.

They control `r`, `s`, and `recovery_id` (and hence the y-parity of `R`), but `R` itself is determined by their choice of `r`. So for any chosen `r` and the resulting `R`, they need to find `s` such that `s·R = r·T + z·G`. That reduces to computing `dlog_R(r·T + z·G)`, which is ECDLP. Starting with a chosen `s` yields even a more problematic scenario.

Could you clarify what I'm missing? Is there an attack that doesn't require solving ECDLP, or is the concern more about a misuse pattern (e.g., callers who don't compare the recovered key against an expected value) rather than a mathematical weakness?

**Comment by tarcieri** [comment]
The main attack would be on something like `VerifyingKey::recover_from_prehash_noverify`. If we have a target key `Q`, we can perform the following attack, which is more or less the same as a signature forgery against an attacker who is not computing the hash of the input message but instead trusting one supplied by the attacker:

1. pick arbitrary `u`, `v`
2. compute `R = uQ + vG`
3. compute `r = R.x mod n` and `recovery_id` based on if `R.x` overflows `n`
4. compute `s = r*u^-1`
5. compute `z = r*v*u^-1`

Notably this relies on being able to solve for `z`, so it won't work on the APIs where `z` is computed, like `VerifyingKey::recover_from_msg`

If an attacker doesn't have their choice of `z` they can still find a signature that recovers an invalid `Q` whose dlog they don't know by running the recovery equation with fabricated choices of `r`, `s`, and `recovery_id`.

Without the verification step, there is no proof anyone knows the dlog of `Q`. And that is the core problem.

Anyway, the relevant APIs to shoot yourself in the foot now exist, so I hope we're finally done with this issue?

**Comment by pmikolajczyk41** [comment]
Thanks for the detailed explanation - to be clear, I'm not trying to change anything about the API, just trying to fully understand what the check is guarding against for my own education.

One observation on your first construction: I believe it actually passes `verify_prehash`. The verification computes `X = z·s⁻¹·G + r·s⁻¹·Q`. Substituting your values (`s⁻¹ = u·r⁻¹`, `z = r·v·u⁻¹`):
```
  z·s⁻¹ = v
  r·s⁻¹ = u
  X = v·G + u·Q = R  ✓
```

So the construction produces a signature that genuinely verifies - the check wouldn't have caught it. The real protection in that case is that `z` must be fixed by the caller, not the attacker.

On your second scenario - "fabricated choices of `r`, `s`, `recovery_id` with fixed `z`" - this is the part I'm most curious about, purely mathematically. The recovered key is `Q = r⁻¹(sR − zG)`, which for arbitrary `r`, `s` gives some point nobody knows the dlog of. Instinctively I see that the attacker should be able to do _something_, but I don't see how to turn that into a targeted attack on a specific `Q` without landing back on ECDLP.

**Comment by tarcieri** [comment]
> So the construction produces a signature that genuinely verifies - the check wouldn't have caught it. 

Yes, there are two different issues here: an attacker being able to create a signature that recovers a preselected curve point, and a signature that recovers a point with an unknown dlog. The verification check fundamentally ensures the signature is valid and was actually produced by someone who knows the dlog. I apologize if my hasty reply while on vacation which you are necroposting on multiple years later conflated the two issues.

What attacks are possible are going to depend on the nature of the application using them. It depends what the signatures are being used for. If you are "successfully" recovering public keys from invalid public signatures, hopefully there's a secondary step to actually verify the signature and eliminate such invalid keys. Otherwise you're just treating a signature as a serialization format for compressed curve points.

**Comment by pmikolajczyk41** [comment]
I don't want to overstate my case, but I think [`verify_prehashed`](https://github.com/RustCrypto/signatures/blob/9cabd275ba9769ca0aeed3436bc7ae55a89b7ab1/ecdsa/src/hazmat.rs#L204-L227) in [`recover_from_prehash`](https://github.com/RustCrypto/signatures/blob/9cabd275ba9769ca0aeed3436bc7ae55a89b7ab1/ecdsa/src/recovery.rs#L348-L361) is a tautology: the recovered key is constructed precisely such that verification must succeed.

Given `prehash`, `signature` and `recovery_id`, we have:
```rust
// recovery (recover_from_prehash_noverify):
let (r,s) = signature.split_scalars();
let z = to_scalar(prehash);
let R = decompress(r, recovery_id);
let Q = r⁻¹·(s·R − z·G);                        // u1 = −(r⁻¹·z), u2 = r⁻¹·s
```

And then, using the same `prehash`, `signature`, `recovery_id` and the new `Q`:

```rust
// verification (verify_prehashed)
let (r,s) = signature.split_scalars();  // as before
let z = to_scalar(prehash);             // as before

let u1 = z·s⁻¹;
let u2 = r·s⁻¹;
let x = u1·G + u2·Q
     = z·s⁻¹·G + r·s⁻¹·Q // substituting the Q from recovery
     = z·s⁻¹·G + r·s⁻¹·(r⁻¹·(s·R − z·G))
     = z·s⁻¹·G + R - z·s⁻¹·G
     = R
```

While using `verify_prehashed` is required in other places like `trial_recovery_from_prehash`, it seems that it cannot catch any input that successfully yields some public key.

Btw, this stops looking like a tautology if we would use `vk.verify_prehash(prehash, signature)?;` instead of direct call to `hazmat::verify_prehashed`. The former additionally does an optional high-s check.

**Comment by tarcieri** [comment]
The low-S normalization logic being in `VerifyingKey::verify_prehash` instead of `hazmat::verify_prehashed` is a good point. I'm not sure why it's like that; it must be a legacy vestige. I can move the check into the latter.

I will have to think more about if the signature verification check is truly tautological and can be removed. Perhaps you can open a new issue with your explanation.

Edit: this moves the low-S normalization check to `hazmat::verify_prehashed`, though such a check could even be added to `recover_from_prehash_noverify`: https://github.com/RustCrypto/signatures/pull/1379
